
services:
  logs:
    environment:
      - LOGGER_NAME=$LOGGER_NAME
      - REPOSITORY_ROOT=$REPOSITORY_ROOT
      - STRUDEL_TEMP_DIR=$STRUDEL_TEMP_DIR
      - HASHER_STORAGE_TYPE=$HASHER_STORAGE_TYPE
    container_name: logs
    image: 446759808364.dkr.ecr.eu-central-1.amazonaws.com/shtruddel:latest
    expose:
      - "8000"
      - "8080"
    command: [ "sh", "-c", "python --version && python manage.py migrate && python manage.py runserver 0.0.0.0:8080" ]

  templates:
    environment:
      - LOGGER_NAME=$LOGGER_NAME
      - REPOSITORY_ROOT=$REPOSITORY_ROOT
      - STRUDEL_TEMP_DIR=$STRUDEL_TEMP_DIR
      - HASHER_STORAGE_TYPE=$HASHER_STORAGE_TYPE
    container_name: templates
    image: 446759808364.dkr.ecr.eu-central-1.amazonaws.com/shtruddel:latest
    expose:
      - "8000" # should we remove that in prod?
      - "8080"
    command: [ "sh", "-c", "python --version && python manage.py migrate && python manage.py runserver 0.0.0.0:8080" ]


  nginx:
    image: 446759808364.dkr.ecr.eu-central-1.amazonaws.com/shtruddel_nginx:latest
    container_name: nginx_proxy
    tty: true
    depends_on:
      - templates
    ports:
        - "0.0.0.0:8080:80"
