
services:
  logs:
    environment:
      - LOGGER_NAME=$LOGGER_NAME
      - REPOSITORY_ROOT=$REPOSITORY_ROOT
      - STRUDEL_TEMP_DIR=/tmp
      - HASHER_STORAGE_TYPE=$HASHER_STORAGE_TYPE
      - STRUDEL_USER_ACCESS_KEY_ID=$STRUDEL_USER_ACCESS_KEY_ID
      - STRUDEL_USER_SECRET_KEY=$STRUDEL_USER_SECRET_KEY
      - ENABLE_LOGGING_CODE_UPDATE="True"

    container_name: logs
    image: 446759808364.dkr.ecr.eu-central-1.amazonaws.com/shtruddel:$IMAGE_TAG
    expose:
      - "8000"
      - "8080"
    command: [ "sh", "-c", "python --version && python manage.py migrate && python manage.py  runserver 0.0.0.0:8080" ]

  templates:
    environment:
      - LOGGER_NAME=$LOGGER_NAME
      - REPOSITORY_ROOT=$REPOSITORY_ROOT
      - STRUDEL_TEMP_DIR=/tmp
      - HASHER_STORAGE_TYPE=$HASHER_STORAGE_TYPE
      - STRUDEL_USER_ACCESS_KEY_ID=$STRUDEL_USER_ACCESS_KEY_ID
      - ENABLE_LOGGING_CODE_UPDATE="True"
    container_name: templates
    image: 446759808364.dkr.ecr.eu-central-1.amazonaws.com/shtruddel:$IMAGE_TAG
    expose:
      - "8000" # should we remove that in prod?
      - "8080"
    command: [ "sh", "-c", "python --version && python manage.py migrate && python manage.py runserver 0.0.0.0:8080" ]


  nginx:
    image: 446759808364.dkr.ecr.eu-central-1.amazonaws.com/shtruddel_nginx:$IMAGE_TAG
    container_name: nginx_proxy
    tty: true
    depends_on:
      - templates
    ports:
        - "0.0.0.0:8080:80"
