name: 'Get public strudel files'
description: 'Get public strudel files from strudel-public repository'
runs:

    using: 'composite'

    steps:
      - name: get_public_files 1
        shell: bash
        env:
          version_tag: ${{ env.ref }}
        run: |
            echo "*** version_tag=$version_tag"
            file=docker_compose_run.yml
            {
              if [[ $version_tag == v0* ]]; then
                url="https://raw.githubusercontent.com/strudelbots/strudel-public/refs/tags/$version_tag/"            
              else
                url="https://raw.githubusercontent.com/strudelbots/strudel-public/refs/heads/$version_tag/"            
              fi
            }
            echo "url=$url$file"
            wget  -P /tmp $url$file
            {
              wget_result=$?
              if [ $wget_result -ne 0 ]; then
                echo "Failed to get files from strudel-public with $wget_result"
                exit 1
              fi
            } 
            ls -alt /tmp/$file
            file=github_run_strudel.py
            echo "url=$url$file"
            wget  -P /tmp $url$file
            {
              wget_result=$?
              if [ $wget_result -ne 0 ]; then
                echo "Failed to get files from strudel-public with $wget_result"
                exit 2
              fi
            } 
            ls -alt /tmp/$file
      - name: get_public_files 2
        shell: bash
        run: | 
          cd /tmp
          git clone https://github.com/strudelbots/strudel-public.git
          ls -alt
#
#      - name: check chekout files
#        shell: bash
#        run: |
#            echo "pwd=$(pwd)"
#            ls -alt


#            file=github_run_strudel.py
#            echo "url=$url$file"
#            wget  -P /tmp $url$file
#            {
#              wget_result=$?
#              if [ $wget_result -ne 0 ]; then
#                echo "Failed to get files from strudel-public with $wget_result"
#                exit 2
#              fi
#            }
#            ls -alt /tmp/$file

