name: 'Extract Branch Name'
description: 'Extract the branch name '
runs:
    using: 'composite'
    steps:
      - name: Extract client branch name
        shell: bash
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
        id: extract_branch



