name: 'Check user keys'
description: 'A composite action that install python and requests'
runs:
    using: 'composite'
    steps:
      - name: check-access-key
        shell: bash
        if: ${{ env.strudel_access_key == '' }}
        run: |
          echo STRUDEL_ACCESS_KEY_ID is not defined!
          echo Please follow instruction in strudel-manual XXX
          exit 1
      - name: check-secret-key
        shell: bash
        if: ${{ env.strudel_secret_key == '' }}
        run: |
          echo STRUDEL_SECRET_KEY is not defined!
          echo Please follow instruction in strudel-manual XXX
          exit 1

