name: 'Login to ECR'
description: 'Login to AWS ECR'
runs:
    using: 'composite'
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.strudel_access_key }}
          aws-secret-access-key: ${{ env.strudel_secret_key }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


