name: 'Install Python'
description: 'A composite action that install python and requests'
runs:
    using: 'composite'
    steps:
      - name: install python
        uses: actions/setup-python@v5
        with:
           python-version: '3.10.12'

      - name: Install requests
        shell: bash
        run: pip install requests -q

      - name: Install dataclasses-json
        shell: bash
        run: pip install dataclasses-json -q
