name: 'Get All Files in Repository'
description: 'Get all files'
inputs:
  master_branch:
    description: 'The name of the master branch'
    required: true
  excluded_directories:
    description: '+ seperated list of directory names'
    required: true

runs:

    using: 'composite'
    steps:
      - name: get all files
        id: get-al-files
        shell: bash
        run: |
          echo "Get all files in repository"
          repository=$GITHUB_REPOSITORY
          out_file=${{ env.changed_files }}
          echo "Changed files file: out_file"
          echo "repository=$repository"
          echo "branch=${{ env.branch }}"
          excluded_directories=${{ inputs.excluded_directories }}
          echo "excluded directories=$excluded_directories"
          git checkout $branch
          sleep 1
          source "$RUNNER_TEMP/functions_for_analyzing_git_db.sh"
          python_files=$(find . -name '*.py')
          unique_files=$(args_to_space_separated_string "${python_files[@]}")
          echo "$unique_files"
          count=$(echo $unique_files | wc -w)
          echo "Total files found: $count"
          filtered_files=$(filter_files "$unique_files" "$excluded_directories")
          echo "Files that need to be analyzed by Strudel after filtering:"
          #echo "$filtered_files"
          echo "$filtered_files" >> $out_file
          cat $out_file

          
          
