name: 'Login to ECR'
description: 'Login to AWS ECR'
runs:
    using: 'composite'
    steps:
      - name: Ruin add logs sanity test
        shell: bash
        run: |
          echo "***   start sanity test"
          export STATUSCODE=$(curl --silent --output /dev/null --write-out "%{http_code}" --location '127.0.0.1:8080/add_logs/' \
          --header 'X-Request-Id: 7' \
          --header 'Content-Type: application/json' \
          --data '{"source": "test",
          "file_content": "def foo():\n  print(a)",
          "file_name": "test"}')
          printf "\n***   status code is $STATUSCODE \n"
          if [ $STATUSCODE -ne 200 ]; then echo "sanity test fails, status $STATUSCODE"; fi
          if [ $STATUSCODE -ne 200 ]; then exit 22; fi
          echo "***   end sanity test"



