name: 'Run docker compose'
description: 'Run docker compose for strudel logs'
inputs:
  version_tag:
    description: 'Version tag for strudel-public'
    required: true
    type: string
runs:
  using: 'composite'
  steps:
      - name: Run docker compose
        shell: bash
        run: |
          repository=${{ github.repository }}
          echo "version_tag=${{ inputs.version_tag }}"
          cd /tmp
          {
          if [[ $repository = "strudelbots/strudel-public" ]]; then 
            echo "image_tag=v-0.0.1-b-1"
            echo "image_tag=v-0.0.1-b-1" >> $GITHUB_ENV
          else 
            touch __init__.py
            python3 get_image_for_tag.py ${{ inputs.version_tag }}
          fi
          }




