name: 'Run docker compose'
description: 'Run docker compose for strudel logs'
runs:
  using: 'composite'
  steps:
      - name: Run docker compose
        shell: bash
        run: |
          cd /tmp
          touch __init__.py
          python3 get_image_for_tag.py
    




