name: 'Get image tag for strudel-public'
description: 'Get image tag for strudel-public'
inputs:
  version_tag:
    description: 'Version tag for strudel-public'
    required: true
    type: string
runs:
  using: 'composite'
  steps:
      - name: Run docker compose
        shell: bash
        run: |
          repository=${{ github.repository }}
          echo "version_tag=${{ inputs.version_tag }}"
          cd /tmp
          {
          if [[ $repository = "strudel0000bots/strudel-public" ]]; then 
            echo "image_tag=v-0.0.1-b-1"
            echo "image_tag=v-0.0.1-b-1" >> $GITHUB_ENV
          else 
            touch __init__.py
            version_tag=${{ inputs.version_tag }}
            output=$(python3 get_image_for_tag.py 7.7.7)
            echo "image_tag=$output"
            exit 77
          fi
          }


# tag testing 1

