name: 'extract_strudel_version'
description: 'A composite action that install python and requests'
runs:
    using: 'composite'
    steps:
      - name: extract_strudel_version
        shell: bash
        run: |
          workflow_ref=${{ github.workflow_ref }}
          repository="${{ github.repository }}/"
          echo "repository=$repository"
          repo_ref="@${{ github.ref }}"
          echo "repo_ref=$repo_ref"
          workflow_path=${workflow_ref#"$repository"}
          echo "workflow_path=$workflow_path"
          workflow_path=${workflow_path%"$repo_ref"}
          cat ${workflow_path} > /tmp/my_file
          cat /tmp/my_file
          grep_result=$(grep -F "uses: strudelbots/strudel-public/.github/workflows/run_strudel_test.yml")
          echo "grep_result=$grep_result"
          exit 88
          {
           if [ -z "$grep_result" ]; then
              echo "grep_result=$grep_result"
              exit 7
          }
          exit 8
          
          ref=$(cat ${workflow_path} | grep -F "uses: strudelbots/strudel-public/.github/workflows/run_strudel_test.yml"| cut -d"@" -f2)
          echo "***    Strudel =$ref  ***"
          echo "ref=${ref}" >> $GITHUB_ENV
