name: 'Get Changed Files'
description: 'Login to AWS ECR'
runs:
    using: 'composite'
    steps:
      - name: List all changed files
        id: list-changed-files
        shell: bash
        run: |
          git diff --diff-filter=AMR --name-only origin/main origin/${{ env.branch }}
          {
          echo 'ALL_CHANGED_FILES<<EOF'
          git diff --diff-filter=AMR --name-only origin/main origin/${{ env.branch }}
          echo EOF
          } >> $GITHUB_ENV



