name: 'Get Changed Files'
description: 'Get changed files'
inputs:
  master_branch:
    description: 'The name of the master branch'
    required: true
runs:

    using: 'composite'
    steps:
#      - name: checkout
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
      - name: List changed files 1
        id: list-changed-files
        shell: bash
        run: |
          repository=$GITHUB_REPOSITORY
          echo "repository=$repository"
          echo "master_branch=${{ inputs.master_branch }}"
          echo "branch=${{ env.branch }}"
          master_branch=${{ inputs.master_branch }}
  
          git_command="git diff --name-status origin/$master_branch origin/${{ env.branch }}"
          echo "** git command is: 
          echo "$git_command"
          eval " $git_command"
