name: 'Get Changed Files'
description: 'Login to AWS ECR'
inputs:
  master_branch:
    description: 'The name of the master branch'
    required: true
runs:

    using: 'composite'
    steps:
      - name: List all changed files
        id: list-changed-files
        shell: bash
        run: |
          echo "repository: "${{ env.repository }}
          echo "master_branch=${{ inputs.master_branch }}"
          master_branch=${{ inputs.master_branch }}
          origin="origin/" 
          {
            if [[  $master_branch == "refs/tag*" ]]; then origin=""; fi
          }
          git diff --diff-filter=AMR --name-only origin/$master_branch origin/${{ env.branch }}
          {
          echo 'ALL_CHANGED_FILES<<EOF'
          git diff --diff-filter=AMR --name-only origin/$master_branch origin/${{ env.branch }}
          echo EOF
          } >> $GITHUB_ENV


