name: 'Get Changed Files'
description: 'Login to AWS ECR'
inputs:
  master_branch:
    description: 'The name of the master branch'
    required: true
runs:

    using: 'composite'
    steps:
#      - name: checkout
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0

      - name: List all changed files
        id: list-changed-files
        shell: bash
        run: |
          repository=$GITHUB_REPOSITORY
          echo "repository=$repository"
          echo "master_branch=${{ inputs.master_branch }}"
          echo "branch=${{ env.branch }}"
          master_branch=${{ inputs.master_branch }}
          current_branch=${{ env.ref }}
          {
            if [[ $current_branch == v0* ]] || [[ $current_branch == refs\/tag* ]]; then  
              echo "current_branch is refs/tags: $current_branch"
              origin="" 
            elif [[ $repository = "strudelbots/strudel-public" ]]; then
              origin="origin"
              master_branch="main"
              echo "repository: $repository, origin: $origin, master_branch: $master_branch"
            else
              echo "repository is not strudelbots/strudel-public: $repository"
              exit 23
            fi
          }
          echo "**** git diff --diff-filter=AMR --name-only $origin/$master_branch $origin/${{ env.branch }}"
          #git diff --diff-filter=AMR --name-only origin/main origin/pre-release-v0.10.0
          command="diff --diff-filter=AMR --name-only $origin/$master_branch $origin/${{ env.branch }}"
          git $(command)
          #{
          #  echo 'ALL_CHANGED_FILES<<EOF'
          #  #git diff --diff-filter=AMR --name-only originmain origin/pre-release-v0.10.0
          #  git diff --diff-filter=AMR --name-only $origin$master_branch $origin${{ env.branch }}
          #  echo EOF
          #} >> $GITHUB_ENV


