name: client side run strudel test
# version 0.24.03
on:
  workflow_dispatch:
    inputs:
      user_command:
        description: "insert 'test-strudel' to run this job"
        required: true
  push:
      branches:
        - '**'
        - (!main)
jobs:
  should_run_strudel:
    runs-on: ubuntu-22.04
    outputs:
      run_strudel: ${{ steps.user_command.outputs.RUN_STRUDEL }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: check user command
        id: user_command
        shell: bash
        run: |
          echo "Working branch:" ${{ github.ref }}
          user_command=${{ inputs.user_command }} 
          user_command=${user_command^^}
          last_commit=$(git log -1 --pretty=%B $sha_last_commit)
          last_commit=${last_commit^^}
          echo "last_commit: $last_commit"
          {
          if [[ $user_command == *"TEST-STRUDEL"* ]]; then
            echo "Run strudel with cli command: $user_command"
            echo "RUN_STRUDEL=$user_command" >> $GITHUB_OUTPUT
          elif [[ $last_commit == *"TEST-STRUDEL"* ]]; then
              echo "Run strudel-test by commit message"
              echo "RUN_STRUDEL=TEST-STRUDERL" >> $GITHUB_OUTPUT
          else
            echo "RUN_STRUDEL=none" >> $GITHUB_OUTPUT
            echo "No strudel test requested, to run strudel test, please include 'TEST-STRUDEL' in your command"
          fi
          }
  run-strudel-test:
    needs: [ should_run_strudel ]
    if: ${{ needs.should_run_strudel.outputs.run_strudel!='none' }}
    uses: strudelbots/strudel-public/.github/workflows/run_strudel_test.yml@v0.24.04
    with:
      master_branch: main
    secrets:
        strudel_access_key: ${{ secrets.STRUDEL_ACCESS_KEY_ID }}
        strudel_secret_key: ${{ secrets.STRUDEL_SECRET_KEY }}


