name: run strudel-test
on:
  workflow_dispatch:
  push:
jobs:
  run-strudel-test:
    uses: strudelbots/strudel-public/.github/workflows/run_strudel_test.yml@add-doccker-logs-enf-of-job
#    uses: strudelbots/strudel-public/.github/workflows/run_strudel_test.yml@v0.11.11
    with:
      logger_name: ansible
      master_branch: main
    secrets:
        strudel_access_key: ${{ secrets.STRUDEL_ACCESS_KEY_ID }}
        strudel_secret_key: ${{ secrets.STRUDEL_SECRET_KEY }}

