name: run strudel-for-logs
on:
  workflow_dispatch:
    inputs:
      user_command:
        description: 'The user request'
        required: true

  push:
    branches:
      - "**"
      - '!main'
jobs:
  should_run_strudel:
    runs-on: ubuntu-22.04
    outputs:
      run_strudel: ${{ steps.user_command.outputs.RUN_STRUDEL }}
    steps:
      - name: check user command
        id: user_command
        shell: bash
        run: |
          echo "Working branch:" ${{ github.ref }}
          user_command=${{ inputs.user_command }} 
          user_command=${user_command^^}
          {
          if [[ $user_command == "ADD-LOGS" || $user_command == "REMOVE_LOGS" ]]; then
            echo "RUN_STRUDEL=$user_command" >> $GITHUB_OUTPUT
          else
            echo "RUN_STRUDEL=none" >> $GITHUB_OUTPUT
            echo "No strudel add/remove logs required, to add/remove logs, please include 'ADD-LOGS' \ 
                  or 'REMOVE-LOGS' in your command"
          fi
          }
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: check head commit message
        id: check_head_commit_message
        env:
          sha_last_commit: ${{ github.event.pull_request.head.sha }}
        shell: bash
        run: |
          last_commit=$(git log -1 --pretty=%B $sha_last_commit)
          echo "last_commit:  $last_commit"
                    {
          if [[ $user_command == *"ADD-LOGS"* ]]; then
            echo "RUN_STRUDEL=add-logs" >> $GITHUB_OUTPUT
          elif [[ $user_command == *"REMOVE-LOGS"* ]]; then
            echo "RUN_STRUDEL=remove-logs" >> $GITHUB_OUTPUT
          else
            echo "RUN_STRUDEL=none" >> $GITHUB_OUTPUT
          fi
          }

          echo "command is $command"
          echo "run_strudel_value=$command" >> "$GITHUB_OUTPUT"

  run-strudel-for-logs:
    needs: [ should_run_strudel ]
    if: ${{ needs.should_run_strudel.outputs.run_strudel!='none' }}
    uses: strudelbots/strudel-public/.github/workflows/run_strudel_for_logs.yml@44-run-addremove-logs-with-gh-cli
    with:
# Make sure to change the name of your master branch if it is not main
      master_branch: main
      user_command: ${{ needs.should_run_strudel.outputs.run_strudel }}
    secrets:
      strudel_access_key: ${{ secrets.STRUDEL_ACCESS_KEY_ID }}
      strudel_secret_key: ${{ secrets.STRUDEL_SECRET_KEY }}

permissions:
  actions: write
  contents: write

