name: run strudel-test
on:
  workflow_dispatch:
  push:
jobs:
  run-strudel-test:
    uses: strudelbots/strudel-public/.github/workflows/run_strudel_test.yml@8-change-run-logs-to-use-reusable-actions
    secrets:
        strudel_access_key: ${{ secrets.STRUDEL_ACCESS_KEY_ID }}
        strudel_secret_key: ${{ secrets.STRUDEL_SECRET_KEY }}
