name: run strudel-test
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
      - (!main)
jobs:
  run-strudel-test:
    uses: strudelbots/strudel-public/.github/workflows/client_side_file_change_test.yml@emerix-test-changed-files
    with:
      # Make sure to change the name of your master branch if it is not main
      master_branch: main

