name: run strudel-test
on:
  workflow_dispatch:
  push:
jobs:
  run-strudel-test:
    uses: strudelbots/strudel-public/.github/workflows/run_strudel_test.yml@v0.12.01
    with:
      # Make sure to change the name of your master branch if it is not main
      master_branch: main
      use_dev_ecr_repository: true
    secrets:
        strudel_access_key: ${{ secrets.STRUDEL_ACCESS_KEY_ID }}
        strudel_secret_key: ${{ secrets.STRUDEL_SECRET_KEY }}

