name: run strudel-test
on:
  workflow_dispatch:
    inputs:
      user_command:
        description: 'The user request'
        required: true
  push:
      branches:
        - '**'
        - (!main)
jobs:
  should_run_strudel:
    runs-on: ubuntu-22.04
    outputs:
      run_strudel: ${{ steps.check_head_commit_message.outputs.run_strudel_value }}
    steps:
      - name: check user command
        id: check_head_commit_message
        shell: bash
        run: |
          user_command=${{ inputs.user_command }} 
          user_command=${user_command^^}
          if [[ ${{ inputs.user_command == *ADD-LOGS"* ]] then;
            echo "add-logs" 
          else
            echo "no-add-logs"
          fi
          echo "command is ${{ inputs.user_command }}"
          echo "run_strudel_value=$command" >> "$GITHUB_OUTPUT"

#  run-strudel-test:
#    uses: strudelbots/strudel-public/.github/workflows/run_strudel_test.yml@v0.14.03
#    with:
#      master_branch: main
#    secrets:
#        strudel_access_key: ${{ secrets.STRUDEL_ACCESS_KEY_ID }}
#        strudel_secret_key: ${{ secrets.STRUDEL_SECRET_KEY }}

