name: run-strudel-test

on:
  workflow_call:
    inputs:
      logger_name:
        default: 'strudel'
        required: false
        type: string
        description: 'The name of the logger to use'
    secrets:
      strudel_access_key:
        required: true
      strudel_secret_key:
        required: true
  workflow_dispatch:
jobs:
  run-strudel-test:
    runs-on: ubuntu-22.04
    env:
      strudel_access_key: ${{ secrets.strudel_access_key }}
      strudel_secret_key: ${{ secrets.strudel_secret_key }}
    steps:
      - uses: actions/checkout@v4
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch name
        shell: bash
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: extract strudel version
        id: extract-strudel-version
        uses: strudelbots/strudel-public/.github/actions/extract-strudel-version@main

      - name: print ref
        run: |
           echo "env ref=${{ env.ref }}"

      - name: get strudel-public files
        uses: strudelbots/strudel-public/.github/actions/get-public-files@5-map-action-to-specific-strudel-image
#        shell: bash
#        env:
#          version_tag: ${{ env.ref }}
#        run: |
#            url="https://raw.githubusercontent.com/strudelbots/strudel-public/refs/heads/$version_tag/code/determine_strudel_action.sh"
#            echo "url=$url"
#            wget -q -P /tmp $url
#            {
#              wget_result=$?
#              if [ $wget_result -ne 0 ]; then
#                echo "Failed to get files from strudel-public with $wget_result"
#                exit 1
#              fi
#            }
#
#            ls -alt /tmp/determine_strudel_action.sh
#      - name: Clone the Strudel manager Repository
#        run: |
#          export current_dir=$(pwd)
#          cd /tmp
#          git clone https://github.com/strudelbots/strudel-public.git
#          cd strudel-public
#          ls -alt
#          cd $current_dir
#      - name: install python
#        id: install-python
#        uses: strudelbots/strudel-public/.github/actions/install-python@main
#
#
#      - name: Install requests
#        run: pip install requests -q


#      - name: "Check that STRUDEL_ACCESS_KEY_ID exists"
#
#        if: ${{ env.strudel_access_key == '' }}
#        run: |
#          echo STRUDEL_ACCESS_KEY_ID is not defined!
#          echo Please follow instruction in strudel-manual XXX
#          exit 1
#      - name: "Check that STRUDEL_SECRET_KEY exists"
#        if: ${{ env.strudel_secret_key == '' }}
#        run: |
#          echo STRUDEL_SECRET_KEY is not defined!
#          echo Please follow instruction in strudel-manual XXX
#          exit 1

#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          aws-access-key-id: ${{ secrets.strudel_access_key }}
#          aws-secret-access-key: ${{ secrets.strudel_secret_key }}
#          aws-region: eu-central-1
#
#      - name: Login to Amazon ECR
#        id: login-ecr
#        uses: aws-actions/amazon-ecr-login@v2
#
#      - name: run strudel sanity test
#        run: |
#            echo "***   start sanity test"
#            export STATUSCODE=$(curl --silent --output /dev/null --write-out "%{http_code}" --location '127.0.0.1:8080/add_logs/' \
#            --header 'X-Request-Id: 7' \
#            --header 'Content-Type: application/json' \
#            --data '{"source": "test",
#            "file_content": "def foo():\n  print(a)",
#            "file_name": "test"}')
#            printf "\n***   status code is $STATUSCODE \n"
#            if [ $STATUSCODE -ne 200 ]; then echo "sanity test fails, status $STATUSCODE"; fi
#            if [ $STATUSCODE -ne 200 ]; then exit 22; fi
#            echo "***   end sanity test"
#
