name: run-strudel-test

on:
  workflow_call:
    inputs:
      logger_name:
        default: 'strudel'
        required: false
        type: string
      master_branch:
        type: string
        required: true
    secrets:
      strudel_access_key:
        required: true
      strudel_secret_key:
        required: true
  workflow_dispatch:
jobs:
  run-strudel-test:
    runs-on: ubuntu-22.04
    env:
      strudel_access_key: ${{ secrets.strudel_access_key }}
      strudel_secret_key: ${{ secrets.strudel_secret_key }}
    steps:
#      - uses: actions/checkout@v3
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Extract user branch name
        id: exract-branch-name
        uses: strudelbots/strudel-public/.github/actions/get_current_branch@main

      - name: extract strudel version
        id: extract_strudel_version
        uses: strudelbots/strudel-public/.github/actions/extract_strudel_version@main
        with:
          mode: 'test_strudel'

      - name: get strudel-public files
        uses: strudelbots/strudel-public/.github/actions/get_public_files@pre-release-v0.10.0

      - name: check user keys
        uses: strudelbots/strudel-public/.github/actions/check-user-keys@main

      - name: Get changed files
        id: get_changed_files
        uses: strudelbots/strudel-public/.github/actions/get_changed_files_in_branch@pre-release-v0.10.0
        with:
          master_branch: ${{ inputs.master_branch }}

      - name: install python
        id: install-python
        uses: strudelbots/strudel-public/.github/actions/install-python@main

      - name: login to ecr
        uses: strudelbots/strudel-public/.github/actions/login-to-ecr@main

      - name: run docker compose
        run: |
            export LOGGER_NAME=${{ inputs.logger_name }}
            export REPOSITORY_ROOT=${{ github.workspace }}
            export HASHER_STORAGE_TYPE=s3
            export STRUDEL_USER_ACCESS_KEY_ID=${{ secrets.strudel_access_key }}
            export STRUDEL_USER_SECRET_KEY="${{ secrets.strudel_secret_key }}"
            docker compose -f /tmp/docker_compose_run.yml up  -d --quiet-pull
            sleep 15
            docker ps -a

      - name: sanity tests
        uses: strudelbots/strudel-public/.github/actions/sanity_tests@main
